apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: configuration.pipeline-service.io
spec:
  reference:
    workspace:
      exportName: settings-configuration.pipeline-service.io
      # TODO: the path needs to match the location of the apiexport
      path: root:default:pipeline-service-compute
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
    state: Accepted
  - group: "networking.k8s.io"
    resource: networkpolicies
    state: Accepted
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity
    identityHash: "36d45824f68eba565152ccf6a07f17a45d0d6d34d0c5642046eee6f55ec2f961"
  - group: ""
    resource: "resourcequotas"
    state: Accepted
  - group: ""
    resource: "namespaces"
    state: Accepted
