apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: configuration.pipeline-service.io
spec:
  latestResourceSchemas:
    - today.settings.configuration.pipeline-service.io
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
  - group: "networking.k8s.io"
    resource: networkpolicies
    # identityHash needs to match the export of the workload cluster
    # it can be set with: make patch-identity 
    identityHash: "36d45824f68eba565152ccf6a07f17a45d0d6d34d0c5642046eee6f55ec2f961"
  - group: ""
    resource: "resourcequotas"
  - group: ""
    resource: "namespaces"
